### ISSUE TITLE
Add depandabot

### ISSUE THREAD

**Issue by k-deepak04** [ShwetKhatri2001/AR-Webstore#10]
Dependabot is an automated dependency management tool that helps developers keep their projects up to date by automatically monitoring and updating dependencies when new versions are released. 
@ShwetKhatri2001 please assign this issue to me under GSSoC 23 label i will deliver quality work

**Comment by ShwetKhatri2001** [comment]
Sure @k-deepak04 ! Go ahead and integrate it!
