### ISSUE TITLE
[Feature] Create login/sign up page

### ISSUE THREAD

**Issue by linga66** [ShwetKhatri2001/AR-Webstore#100]
### Description

We can create a login/signup page

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines]
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by ShwetKhatri2001** [comment]
It's not on the priority list for now since first, we want to create a public e-commerce platform and then will make it user-specific.
So, thanks for raising this issue but it can't be picked up at this time.

**Comment by ShwetKhatri2001** [comment]
This issue can be worked upon now. It's open for contributions.

**Comment by Albert-2** [comment]
hey @ShwetKhatri2001
First of all Greateee project man
I would very much like to work on this issue
so can you please assign me the same under codepeak'23
Thank you for considering...... :)

**Comment by ShwetKhatri2001** [comment]
Hey @Albert-2 ! Thanks for showing interest in contributing to this project.
Are you still open to work on this ?

**Comment by Albert-2** [comment]
hey @ShwetKhatri2001
yes I am free and intrested too

**Comment by Albert-2** [comment]
@ShwetKhatri2001 
assign me this issue under codepeak'23
Thank you

**Comment by ShwetKhatri2001** [comment]
Okay, Go ahead. You're assigned. Let me know whenever you need any help.

**Comment by Albert-2** [comment]
hey @ShwetKhatri2001
Posted on msg on discord please check it....

**Comment by ShwetKhatri2001** [comment]
Any updates or issues @Albert-2 ? Today is the last day of `Codepeak23`.

**Comment by Albert-2** [comment]
hey @ShwetKhatri2001
Done with changes will make PR by the end of the day

**Comment by Albert-2** [comment]
hey @ShwetKhatri2001 
i am so sorry you replied my message on discord but i failed to see it 
resulting not able to even set up your project 
once again so sorry...!

**Comment by hollermay** [comment]
I'll look into this. Assign me

**Comment by ShwetKhatri2001** [comment]
Sure, Go ahead.

**Comment by IrfanshaikH-7** [comment]
it some one working on this issue

**Comment by ayann07** [comment]
I would like to work on this under swoc 2024

**Comment by ShwetKhatri2001** [comment]
Any updates or issues @hollermay ? Please try to complete your changes in the next 3 days.

**Comment by ayann07** [comment]
@ShwetKhatri2001 can I work on this?

**Comment by IrfanshaikH-7** [comment]
😮‍💨no updates yet..

**Comment by KhushiAgarwal-01** [comment]
If not done I can work on this issue

**Comment by ShwetKhatri2001** [comment]
Let's give a chance to other contributors now. Assigning you @IrfanshaikH-7 as you commented next.

**Comment by IrfanshaikH-7** [comment]
I'll give you updates of my works , thank you

**Comment by ShwetKhatri2001** [comment]
Completed in PR #239
