### ISSUE TITLE
[Feature] details information about the project

### ISSUE THREAD

**Issue by mandliyarajendra11** [ShwetKhatri2001/AR-Webstore#105]
### Description

i can add details information related to project , like title, price , rating , description , category etc

it will be help full in future when we have more product then user click on any product it navigate to the  singleproduct page
contain information related to the particular product

reference  - 
https://sketchfab.com/3d-models/oversized-drop-shoulder-sweatshirt-c533289593ed4a7094bc2e0cefebde12

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines]
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by ShwetKhatri2001** [comment]
We already have issues #64 and #65 which will cover all the details you've mentioned. The card will have basic details and the separate product page will have more details. 

Kindly go through them and let me know if this issue has something different from them else this can be closed and you can work on those issues when they will be open to be assigned.

**Comment by mandliyarajendra11** [comment]
> We already have issues #64 and #65 which will cover all the details you've mentioned. The card will have basic details and the separate product page will have more details.
> 
> Kindly go through them and let me know if this issue has something different from them else this can be closed and you can work on those issues when they will be open to be assigned.

ek me product card ko mobile responsive banaya ja rhaa hai 
ek me aase or cards add kiye ja rha hai

but mera issue ye h ki ek card ke under or bhi information add karna abhi sird qr code and product image 

so esme jo mobile responsive issue h vo close kar do because vo mera esme already information add karne ke sath pura card redesign karunga 💓

**Comment by ShwetKhatri2001** [comment]
The things you want to add are supposed to be covered under those issues only. Have a look at issue #69 as well.
The assigned contributors are also supposed to do the same. 
So, if you want to work on those then you need to wait for some days until they add the changes they can make. 
There can't be separate issues for the same objective.

**Comment by ShwetKhatri2001** [comment]
Closing this because there are other issues to get the same outcomes.
