### ISSUE TITLE
[Feature] Migrate from React 17 to React 18

### ISSUE THREAD

**Issue by Manice18** [ShwetKhatri2001/AR-Webstore#108]
### Description

I will like to make the version change to the latest react version and make all the necessary changes in the code accordingly so that the website doesn't breaks.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines]
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by ShwetKhatri2001** [comment]
@Manice18 Thanks for raising this issue, but since many of our contributors are comfortable with React v17 I'd not recommend that for now. 
So, it's not on the priority list for now, but I'd like to know if this change can bring a notable difference to our platform if we pick it up now.
