### ISSUE TITLE
[Feature] Show features of the product in 3D viewer via Annotations

### ISSUE THREAD

**Issue by ShwetKhatri2001** [ShwetKhatri2001/AR-Webstore#111]
### Description

To show all important features of the product we can use [Annotations ( Camera Views ) by model-viewer](https://modelviewer.dev/examples/annotations/index.html#cameraViews). 

There will be an `i` button in the bottom-right corner with other buttons on click to which all the annotations ( features ) for that object ( product ) will be shown and they will be hidden once the button is clicked again ( like a toggle ). 
By default on load of the object, they will be hidden. Keep the annotations short and to the point ( not taking too much space ).

Also, keep in mind that different objects will have different positions and text for annotations. 
So, change the component in such a way that it can take all the dynamic annotations-data coming from outside and apply annotations for any object based on that data value.

### Screenshots

You should use [model-viewer-editor](https://modelviewer.dev/editor/) and try adding some hotspots there. 
You will get the code snippet on top of that page. For example, I created some here,

![image](https://github.com/ShwetKhatri2001/AR-Webstore/assets/56475750/381f94bc-7835-4d98-b05a-69e0c0fd4304)

On clicking on the annotations the camera should target that position as shown in this [cameraViews example](https://modelviewer.dev/examples/annotations/index.html#cameraViews). After getting the code from the editor above you need to change it and add event listeners as shown in this example.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines]
- [ ] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by mandliyarajendra11** [comment]
i can work on this issue but need some help because first time working on this type of project

**Comment by Girishbari** [comment]
no assignee on this, assign it to me

**Comment by ShwetKhatri2001** [comment]
Okay, you're assigned @Girishbari.

**Comment by Girishbari** [comment]
Before closing this request I had this suggestion, make the CSS file a bit cleaner or raise a issue, its too messed up currently
