### ISSUE TITLE
 [Feature] Adding a new feature - Chatbot. 

### ISSUE THREAD

**Issue by SrishtiSonam** [ShwetKhatri2001/AR-Webstore#112]
### Description

The chatbot will allow the user to explore the website fully.
It will answer the frequently asked questions.
Show the best use of the website for the user.

**An User Interacting Feature.**

Assign me under Gssoc'23.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines]
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by ShwetKhatri2001** [comment]
It's a good feature @SrishtiSonam. Go ahead ! You're assigned.

**Comment by ShwetKhatri2001** [comment]
I've assigned `level1` for now, but if the changes you make are worth more than that, then you may get more points. 
So, Best of Luck !

**Comment by ShwetKhatri2001** [comment]
Any updates or issues @SrishtiSonam ?

**Comment by ShwetKhatri2001** [comment]
@SrishtiSonam Please try to make your changes and create your PR within the next 3 days.
After that, This issue will be open to other interested contributors.

**Comment by ShwetKhatri2001** [comment]
Let's give other contributors a chance to work on this issue. This issue is open to be assigned now.
