### ISSUE TITLE
[Feature] Color Variants for the Product in 3D

### ISSUE THREAD

**Issue by ShwetKhatri2001** [ShwetKhatri2001/AR-Webstore#113]
### Description

We all have seen how e-commerce platforms provide different variants of the same product to fulfill the color requirements of the user, where for the same design / material you get different color combinations. Why not provide this in 3D !

So, the idea is to provide an option ( dropdown for now ) to change product variants.
For reference, you should take a look at [model-viewer shoes-variants example](https://modelviewer.dev/examples/scenegraph/#variants) and try out the shoe variants there. 
Similar to this, the chair present currently on our platform also has two variants and we can create new variants on https://modelviewer.dev/editor/ as well, just as I created one here by changing different material's colors,

![image](https://github.com/ShwetKhatri2001/AR-Webstore/assets/56475750/aba37ec0-d1c7-46da-af0f-23c348d3357f)

If you are creating new variants then you need to `Download Scene` from the editor to get updated `.glb` file. 
After that, you can use the code implementation they have provided in the example, where you will first get the list of available variants and then will update `variantName` based on the selected variant in the dropdown / UI.

### Screenshots

This is how the UI should look actually having the image-tabs for each variant,
![image](https://github.com/ShwetKhatri2001/AR-Webstore/assets/56475750/9d76cb3f-85fa-41c6-8046-f526657c205e)

But since we don't have a product-details page you may just add a dropdown for now to change variants between the viewer area and QR code ( on the right corner below the gray viewer area). 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines]
- [ ] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by Srushti-098** [comment]
Hii Shweta!
I am GSSOC'23 contributor.
I would like to work on this feature and would use threejs for this.
Kindly assign it to me.

**Comment by ShwetKhatri2001** [comment]
You can surely work on this but I'd recommend having a look at [model-viewer](https://modelviewer.dev/). Go through the description provided above.

Even I thought of implementing all 3D and AR features using Three.JS . But with model-viewer it's much easier to begin and contribute for everyone, that's why I started with it. So, it will be easy for you as well to implement as it's described there.

**Comment by Srushti-098** [comment]
I have implemented the actual thing for color variations but I am getting some merge conflicts due to some latest changes which I am resolving right now.
![IMG-20230810-WA0006(1)](https://github.com/ShwetKhatri2001/AR-Webstore/assets/97287181/466e0154-a987-41d1-8384-f6d9629d63e1)
![IMG-20230810-WA0007](https://github.com/ShwetKhatri2001/AR-Webstore/assets/97287181/1460ad00-bc9a-4155-b3ac-b08a1ccdc7b9)
![IMG-20230810-WA0010](https://github.com/ShwetKhatri2001/AR-Webstore/assets/97287181/8c5d231c-8b86-4a2a-8b17-461e6d29d26e)

**Comment by ShwetKhatri2001** [comment]
Great work till now! Just find out the changes you need for this feature and have them. Minor changes in other UI elements would be okay until it's not breaking any functionality.
If you want some help then raise a PR, so that I can also look at the merge conflicts.

**Comment by Srushti-098** [comment]
Hi Shwet, I have been working on this issue. I am unable to map the functionality over multiple products right now. Give some time to work on that. Can you suggest any way for that?

**Comment by ShwetKhatri2001** [comment]
Take your time. But if you need some help then you should create a PR so that I can take a look at how you're implementing it and what can be improved.

**Comment by IrfanshaikH-7** [comment]
Hello! are you perhaps looking for something like this

https://github.com/ShwetKhatri2001/AR-Webstore/assets/124655192/c914b46a-4c02-4959-8484-bd4fcbe33a4d

I'd like to look into it can you please assign it to me

**Comment by ShwetKhatri2001** [comment]
Yes, mostly. We can change the colors of different materials present in an object and create variants out of those color combinations.
Try for such implementation if you can OR at least make sure it changes the color of the primary element of the object. For example in a car, it will be car's outer body.
I'm assigning you this issue. Some UI improvements you can also take a look such as color selection buttons.

**Comment by IrfanshaikH-7** [comment]
Ohk. . I was targeting the base meterial color .. 
If there is a variant object somewhere it'll workout if I just Target that right ?..
I look into it! Thankyou for assigning me.

**Comment by ShwetKhatri2001** [comment]
Any updates or issues @IrfanshaikH-7 ?

**Comment by IrfanshaikH-7** [comment]
@ShwetKhatri2001 am really am sorry - I worked on it and implemented it sucessfull - as I got into a confusion or could say a little issue - i got busy with something else and forgot about it

**Comment by IrfanshaikH-7** [comment]
And I would like to confirm one thing from you: do every product has variants or there are any exceptions
?

**Comment by ShwetKhatri2001** [comment]
You can just update the existing models having at least 3 variant options for each one and provide UI to select variants. 
I think you've already done that for one ( chair ), do it for others and it will be good to be merged.

**Comment by IrfanshaikH-7** [comment]
> You can just update the existing models having at least 3 variant options for each one and provide UI to select variants. 
> I think you've already done that for one ( chair ), do it for others and it will be good to be merged.

- I haven't created any variant - the chair had them by default and just used it to map over them - ..but others don't have variants to them 

- think of it like not all products have variants to them

**Comment by ShwetKhatri2001** [comment]
To help you better, I need to review the kind of changes you're making. Please create a PR having your existing work.
I will merge it, if it's good and not breaking anything. We can improve it further then.

**Comment by IrfanshaikH-7** [comment]
@ShwetKhatri2001 oh thankyou so much lets do that I'll pr right now and look into the code and guide me on how can i improve it -

and at the same time could you tell me where have you got those product lists, as I'm thing about adding some more to see if they have varients in them or not too

**Comment by ShwetKhatri2001** [comment]
You can add variants to any .glb model as I described in the issue description.

> Similar to this, the chair present currently on our platform also has two variants and we can create new variants on https://modelviewer.dev/editor/ as well, just as I created one here by changing different material's colors.

I added two variants `Yellow` and `Green` to the `car.glb` model. 
I just gave a new variant name, changed the `body` material color, and did `Download Scene`. The zip file had updated .glb.

<hr/>

<img width="400" alt="Yellow Variant" src="https://github.com/ShwetKhatri2001/AR-Webstore/assets/56475750/0a7e5d3b-d046-42a6-a046-e3a3a1b80086">

<img width="400" alt="Yellow Variant" src="https://github.com/ShwetKhatri2001/AR-Webstore/assets/56475750/f59d09b8-58fa-4952-9f33-a7b93de8e488">
<hr/>

Similarly you can update existing models. To add new ones you can find some free to use models online ( i.e. https://sketchfab.com/ ). Get the .glb, modify them in [model-viewer-editor](https://modelviewer.dev/editor/) and list the details as a product in `src/data/ProductItems.js` to make it available on the platform.

**Comment by IrfanshaikH-7** [comment]
@ShwetKhatri2001  If it's alright with you can I create a separate issue for this saying "feat: Added more models with variants."
as the variant functionality is done, if we  just a some more models with variants in them its easily able to map over them and I'll add some custom variants too

**Comment by IrfanshaikH-7** [comment]
Could you please review my PR
