### ISSUE TITLE
[BUG]: incorrect measurements for component causing elements overflow 🪲 

### ISSUE THREAD

**Issue by 0xabdulkhalid** [ShwetKhatri2001/AR-Webstore#125]
### Description

- The bug is about improper padding and margin values that have been applied for the model viewer component. Due to this the elements are pretend to overflowed at outer region.
- This needs to be resolved otherwise this causes bad impression on User Interface of AR-Webstore Website.

### Screenshots

![image](https://github.com/ShwetKhatri2001/AR-Webstore/assets/92252895/0e003344-8804-4dc7-b925-5c44f41f9245)

### What browser are you seeing the problem on?

Firefox

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by 0xabdulkhalid** [comment]
Hey there @ShwetKhatri2001 👋🏻

Please make sure to assign this issue to me as soon as possible to make the work done quickly.

Thank you!

**Comment by ShwetKhatri2001** [comment]
Yes, the outer card container and inner 3D container should always match in width. This width should not be dependent on the content length or width present inside.

Also, the plus button present in the bottom-right corner is overflowing sometimes.

You can fix all these small bugs with similar kinds of changes I guess, so do fix them all.
