### ISSUE TITLE
[BUG]: improper sizing of buttons on model viewer component 🪲

### ISSUE THREAD

**Issue by 0xabdulkhalid** [ShwetKhatri2001/AR-Webstore#126]
### Description

- This bug is about the improper sizing of buttons on model viewer component.
- Those buttons are not in the right aspect ratio, they seems to be disorted and forced to be shrinked.
- We need to fix this behaviour of buttons to improve the UI of AR-Webstore Website.

### Screenshots

|||
|:---:|:----:|
|**BEFORE**| ![Screenshot 2023-07-23 at 16-37-40 AR-Webstore](https://github.com/ShwetKhatri2001/AR-Webstore/assets/92252895/c7de6f38-f3ef-437c-98d1-062132d84e63)|
|**AFTER**|![Screenshot 2023-07-23 at 16-36-04 AR-Webstore](https://github.com/ShwetKhatri2001/AR-Webstore/assets/92252895/0d1b3029-8131-4326-a3fa-191c4a3af95b) |

### What browser are you seeing the problem on?

Firefox

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by 0xabdulkhalid** [comment]
Hey there @ShwetKhatri2001 👋🏻

Please make sure to assign this issue to me as soon as possible to make the work done quickly.

Thank you!

**Comment by ShwetKhatri2001** [comment]
Sure. 
Also, the size of the buttons are looking different on different browsers. 
On Chrome it looks decent but can be improved and on Firefox it's looking bad.

So, make the changes keeping this in mind and make sure they look similar in all the browsers ( specially Chrome and Firefox ).
