### ISSUE TITLE
Add Template for creating new issue

### ISSUE THREAD

**Issue by k-deepak04** [ShwetKhatri2001/AR-Webstore#13]
i can creat one template for creating the issue so it would be in proper format
with idea/functionality and bug as option

![image](https://github.com/ShwetKhatri2001/AR-Webstore/assets/96341431/e6bb64da-496c-44d8-8e93-22b2749bce10)
![image](https://github.com/ShwetKhatri2001/AR-Webstore/assets/96341431/e6050e88-e0b8-480b-b526-43243a4743a9)

this will help to properly describe issue and maintain proper code of conduct rather than random issue generating

**Comment by k-deepak04** [comment]
@ShwetKhatri2001 i'll issue a PR soon :)

**Comment by k-deepak04** [comment]
@ShwetKhatri2001 i have added the commit but it was merged in the depandabot PR
what to do?

**Comment by ShwetKhatri2001** [comment]
You should create a new branch for new issue you pick. so do that. 
Remove the changes related to this issue from that PR and raise new PR with those changes.

**Comment by k-deepak04** [comment]
okay will do that

**Comment by k-deepak04** [comment]
@ShwetKhatri2001 please merge this pr then i will create next

**Comment by k-deepak04** [comment]
@ShwetKhatri2001 this is the issue i have commited
https://github.com/k-deepak04/AR-Webstore/commit/5b36602303e51ba53d9034dadf8229f8980697af
