### ISSUE TITLE
[DOCS]: MAKE GSSOC BANNER DYNAMIC FOR LIGHT/DARK GH THEME 📝✨ 

### ISSUE THREAD

**Issue by 0xabdulkhalid** [ShwetKhatri2001/AR-Webstore#131]
### Description

 - This improvement is about making the GSSOC Banner responsive to Dark/Light mode.
- This helps us to make the documentation better to the readers, and images are also in high quality so devices with larger screens can be read the documentation without image disortion.

### Screenshots

![image](https://github.com/ShwetKhatri2001/AR-Webstore/assets/92252895/b80ad80e-37bc-4460-b8bf-5e9d4cbbf784)

### Changes i want to make

| DESIRED STATE IN LIGHT THEME | DESIRED STATE IN DARK THEME |
|  :-----:   | :-----:  |
| ![image](https://github.com/priyankarpal/ProjectsHut/assets/92252895/79446834-60ae-4394-b743-ae4e782c134e) | ![](https://user-images.githubusercontent.com/63473496/213306279-338f7ce9-9a9f-4427-8c2a-3e344874498f.png) 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines]
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by 0xabdulkhalid** [comment]
@ShwetKhatri2001 Make sure to assign this issue to me to make documentation better!

**Comment by ShwetKhatri2001** [comment]
Okay, Go ahead and make the change. You're assigned.
