### ISSUE TITLE
[BUG] Footer and card is overlapping 

### ISSUE THREAD

**Issue by Prajwal0225** [ShwetKhatri2001/AR-Webstore#139]
### Description

The card is overlapping with fotter footer

### Screenshots

![image](https://github.com/ShwetKhatri2001/AR-Webstore/assets/103810119/ea10a49e-8082-48d5-9bdf-554807d68f53)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by ShwetKhatri2001** [comment]
Yes, we need a responsive grid view of the container having cards for any number of cards. 
Someone who has worked on a similar thing earlier can easily fix this. 
Assigning you since you've shown interest to solve it.
