### ISSUE TITLE
[BUG]: Noticed Except feature-request.yml File, Remains all Have Minor Bugs in ISSUE TEMPLATES⚠⚠

### ISSUE THREAD

**Issue by NarendraKoya999** [ShwetKhatri2001/AR-Webstore#140]
### Description

- **I have Observed except feature-request.yml File, Remaining 3 Files are having Minor Bugs/Issues in GitHub Issue Templates Folder.**
- **This Below Screenshot explains Contributed Link is not fit to Our Repository existed in bug-report.yml File..**
- **Remain 2 Files are Having Some Indentation Problems.**

### Screenshots

![arweb-1](https://github.com/ShwetKhatri2001/AR-Webstore/assets/84512164/36fc8af1-ba6d-436b-908b-023eb4e11593)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by NarendraKoya999** [comment]
Hi @ShwetKhatri2001 . Please Review on this Issue as soon as Possible. Thank You !

**Comment by ShwetKhatri2001** [comment]
Okay, I have found those bugs as well. You can start fixing them.
Check https://github.com/ShwetKhatri2001/AR-Webstore/pull/134#issuecomment-1670724221 and I can assign Level-1 for this since some of the bugs got introduced by you only when you added new template files.
