### ISSUE TITLE
[FEATURE]  I will work on Header since it's alignment is not proper i will try to make it better.

### ISSUE THREAD

**Issue by Aakaassh** [ShwetKhatri2001/AR-Webstore#155]
### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ShwetKhatri2001/AR-Webstore/blob/master/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by ShwetKhatri2001** [comment]
Go ahead @Aakaassh, you can work on it. 
Also, just to clarify you've marked yourself as a GSSoC'23 contributor. 
But since the GSSoC'23 contribution period is over now, your contribution will not considered for that. 
Otherwise, your contributions are always welcome.

**Comment by Jaimin25** [comment]
I would like to work on this, please assign it to me

**Comment by ShwetKhatri2001** [comment]
Closing this because the issue is already resolved.
