### ISSUE TITLE
Footer is not Responsive 

### ISSUE THREAD

**Issue by Devesh-Daku** [ShwetKhatri2001/AR-Webstore#169]
### What's the style idea?

i'd like to suggest we can have a better footer with this project 

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ShwetKhatri2001/AR-Webstore/blob/master/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ShwetKhatri2001/AR-Webstore/blob/master/CODE_OF_CONDUCT.md)
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by ayann07** [comment]
As a KWOC Contributor, I would want to work on this issue.

**Comment by Devesh-Daku** [comment]
Please assign a codepeak label

**Comment by ShwetKhatri2001** [comment]
I don't think Footer need a lot of improvement, so I've kept the issue of this issue as easy. 
Although, I am open to change it based on the level of improvement.

**Comment by Devesh-Daku** [comment]
sure

**Comment by Devesh-Daku** [comment]
Please wait , today evening i'll send pr
