### ISSUE TITLE
security.txt 

### ISSUE THREAD

**Issue by pinak22dhir** [ShwetKhatri2001/AR-Webstore#170]
### Description

add privacy.md file

### Screenshots

can i add security.txt file or privacy.md file

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by ShwetKhatri2001** [comment]
Go ahead and add it. You're assigned.

**Comment by ShwetKhatri2001** [comment]
Are you a participating in any program ? Any of Codepeak or KWOC ?

**Comment by pinak22dhir** [comment]
kwoc

**Comment by ShwetKhatri2001** [comment]
Any updates or issues @pinak22dhir ?

**Comment by pinak22dhir** [comment]
did add it @ShwetKhatri2001
