### ISSUE TITLE
Add an "About Us" page

### ISSUE THREAD

**Issue by Surajit0573** [ShwetKhatri2001/AR-Webstore#171]
### Description

Currently About Us page is directly redirecting GitHub page. I want to add a separate About Us page with all the information given in the Git Hub.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines]
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by ShwetKhatri2001** [comment]
Great, I was thinking of updating it already. You can start working on it. The details will be similar to shown in the README.md file.
