### ISSUE TITLE
[style]: Center the product list

### ISSUE THREAD

**Issue by Preeti8021** [ShwetKhatri2001/AR-Webstore#175]
### What's the style idea?

It is better to align the products center of the page for better user experience.

### Add screenshots

<img width="943" alt="image" src="https://github.com/ShwetKhatri2001/AR-Webstore/assets/103981488/768d3bc9-78ae-4c0b-941a-4687045f1f7c">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ShwetKhatri2001/AR-Webstore/blob/master/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ShwetKhatri2001/AR-Webstore/blob/master/CODE_OF_CONDUCT.md)
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue under CODEPEAK'23

**Comment by ShwetKhatri2001** [comment]
Yes, makes sense. You can work on it.
