### ISSUE TITLE
[style]: FeedBack Page

### ISSUE THREAD

**Issue by Surajit0573** [ShwetKhatri2001/AR-Webstore#177]
### What's the style idea?

I want to Improve the Feedback Page and make it more visually appealing and responsive.

### Add screenshots

![image](https://github.com/ShwetKhatri2001/AR-Webstore/assets/111490250/80ed1272-f9a3-4c1f-ac5d-c9353a5274de)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ShwetKhatri2001/AR-Webstore/blob/master/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ShwetKhatri2001/AR-Webstore/blob/master/CODE_OF_CONDUCT.md)
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by Surajit0573** [comment]
please assign me under Codepeak 2023, if approved.

**Comment by ShwetKhatri2001** [comment]
Hello, I don't see any improvements needed in UI as such. So, let me know what kind of changes you want to make.

**Comment by Surajit0573** [comment]
> Hello, I don't see any improvements needed in UI as such. So, let me know what kind of changes you want to make.

@ShwetKhatri2001 How About this kind of style with a matching background color !!

![image](https://github.com/ShwetKhatri2001/AR-Webstore/assets/111490250/5b7d2f66-60c2-418a-ace5-daabaf473f0a)

**Comment by ShwetKhatri2001** [comment]
I think the UI doesn't need much improvements, but we can have this functionality - The submitted feedback data should be forwarded to my email similar to the contact us page being implemented on https://github.com/ShwetKhatri2001/AR-Webstore/pull/173 . Let me know if you're interested in implementing that.

**Comment by Yuvraj960** [comment]
Hello @ShwetKhatri2001 , I will implement the issue as you have stated. 
I will forward the submitted feedback to your email using the SMTPJs. 
Assign this issue to me under SWOC24

**Comment by ShwetKhatri2001** [comment]
Okay, you can work on the mentioned changes.
