### ISSUE TITLE
[style]: Navbar Is Not aligned Correct And HamBurger Menu Is Not Working Porper  

### ISSUE THREAD

**Issue by Ayusht777** [ShwetKhatri2001/AR-Webstore#179]
### What's the style idea?

The mobile navbar alignment is off, and the hamburger icon isn't functioning correctly. Clicking it should transform it into a cross icon for proper usability.

### Add screenshots

Add screenshots
![image](https://github.com/ShwetKhatri2001/AR-Webstore/assets/106388215/11102371-23f3-404d-9157-6e19f0e9c529)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ShwetKhatri2001/AR-Webstore/blob/master/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ShwetKhatri2001/AR-Webstore/blob/master/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue
- [ ] I'm a GSSoC'23 contributor

**Comment by Yash-Ainapure** [comment]
@Ayusht777 I would like to work on this issue, could you assign it to me please.

**Comment by ShwetKhatri2001** [comment]
@Yash-Ainapure You can fix this. I'm assigning it to you.

**Comment by Ayusht777** [comment]
This is a preview of the enhanced navbar
![image](https://github.com/ShwetKhatri2001/AR-Webstore/assets/106388215/b43b0b4e-3ac7-4e57-8b75-4fdcf2ceee14)
If you need me to revise some navbar code, I'm available to Do It. Also, could you please label changed  the to "medium"

**Comment by ShwetKhatri2001** [comment]
It's good. What kind of other changes you want to make ?

**Comment by Ayusht777** [comment]
Hey I want To Refactor This Navbar Code Which Will Hey! I want to refactor this navbar code to improve readability and the developer experience. Should I change the label from "Easy" to "Medium," or would it be better to create a new issue for it?

**Comment by ShwetKhatri2001** [comment]
Better to create a new issue for that and first raise the PR for this specific issue.
