### ISSUE TITLE
[Feature] Add a login/signup page

### ISSUE THREAD

**Issue by drockparashar** [ShwetKhatri2001/AR-Webstore#182]
### Description

A login/signup page in this website would increase its functionality.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines]
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by ShwetKhatri2001** [comment]
Hey ! This is a duplicate issue. Have a look at #100 .

**Comment by ShwetKhatri2001** [comment]
Closing this because it's a duplicate issue.
