### ISSUE TITLE
[BUG] Refactoring the Navbar Code

### ISSUE THREAD

**Issue by Ayusht777** [ShwetKhatri2001/AR-Webstore#183]
### Description

It will Increase the Readability of the code 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ShwetKhatri2001/AR-Webstore/blob/master/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by ShwetKhatri2001** [comment]
Okay, go ahead. I am assigning you as an `easy` level issue. The final label will be decided based on the quality of contribution.

**Comment by Ayusht777** [comment]
okay
