### ISSUE TITLE
[style]:Email Input Box Not Algined in Small Screens

### ISSUE THREAD

**Issue by Ayusht777** [ShwetKhatri2001/AR-Webstore#185]
### What's the style idea?

The Email Input Box Should Be in Centered 

### Add screenshots

Add screenshots
![image](https://github.com/ShwetKhatri2001/AR-Webstore/assets/106388215/53237e8b-4f5f-4613-ae79-63e8c419d444)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ShwetKhatri2001/AR-Webstore/blob/master/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ShwetKhatri2001/AR-Webstore/blob/master/CODE_OF_CONDUCT.md)
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by ShwetKhatri2001** [comment]
Sure, you can fix this.

**Comment by Ayusht777** [comment]
![Screenshot (289)](https://github.com/ShwetKhatri2001/AR-Webstore/assets/106388215/8d39edf1-b596-4783-a6a0-06324eaa6073)
Created PR for it
