### ISSUE TITLE
Remodifying contact us page

### ISSUE THREAD

**Issue by Souvik34** [ShwetKhatri2001/AR-Webstore#188]
### Description

The contact us page will be redesigned to look more professional

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines]
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by ShwetKhatri2001** [comment]
This looks a duplicate issue since there is some work in progress as part of https://github.com/ShwetKhatri2001/AR-Webstore/issues/57 .
You may work on that once the assigned person push his changes.

**Comment by ShwetKhatri2001** [comment]
Closing this issue because it's duplicate and inactive.
