### ISSUE TITLE
The contents of nav bar are getting underlined while hovering

### ISSUE THREAD

**Issue by Souvik34** [ShwetKhatri2001/AR-Webstore#189]
### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ShwetKhatri2001/AR-Webstore/blob/master/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by kushwahaPrashant24** [comment]
I want to fix this bug. Please assign this task

**Comment by ShwetKhatri2001** [comment]
That's not an issue, it's expected.

**Comment by Souvik34** [comment]
I have made the it more interesting. I have applied certain transitions to make it cool

**Comment by kushwahaPrashant24** [comment]
It just require a small CSS change 
from text "text-decoration: underline;" to "text-decoration: none;" in "nav a:hover" in header

**Comment by Souvik34** [comment]
@kushwahaPrashant24 the underline effect is expected. So I made the underline transition.

**Comment by ShwetKhatri2001** [comment]
@Souvik34 I think you've already added that in your existing PR. I can merge that.
Let's get that merged first and after that we will come back here if need to improve further.

**Comment by Souvik34** [comment]
Yes I have made the changes in my earlier PR.

**Comment by Souvik34** [comment]
Already merged
