### ISSUE TITLE
need of a logo AR Webstore

### ISSUE THREAD

**Issue by Souvik34** [ShwetKhatri2001/AR-Webstore#190]
### Description

If there is a specific logo then it shall be impressive

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines]
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by ShwetKhatri2001** [comment]
If you want to work on this then research a bit and come up with few options to replace the existing logo.

**Comment by Souvik34** [comment]
I have created few.
If you like those logos then I cant merge them

**Comment by ShwetKhatri2001** [comment]
Send some logo images you've figured out here only before start integrating it.

**Comment by Souvik34** [comment]
![image](https://github.com/ShwetKhatri2001/AR-Webstore/assets/98397984/433feab5-581f-4709-b902-e547b63eb006)
![image](https://github.com/ShwetKhatri2001/AR-Webstore/assets/98397984/331f4166-daa1-4823-99a9-ce05c03b9c05)


These are the two basic drafts.

**Comment by ShwetKhatri2001** [comment]
Okay, you can add the second one.
