### ISSUE TITLE
Redesigning About Us Page 

### ISSUE THREAD

**Issue by PSS2134** [ShwetKhatri2001/AR-Webstore#191]
### What's the style idea?

Change UI and add some Images

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ShwetKhatri2001/AR-Webstore/blob/master/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ShwetKhatri2001/AR-Webstore/blob/master/CODE_OF_CONDUCT.md)
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by PSS2134** [comment]
@ShwetKhatri2001 Assign this to me under Codepeak'23

**Comment by ShwetKhatri2001** [comment]
How you're gonna change it ? Give a good description with examples if possible.

**Comment by PSS2134** [comment]
The About us page looks very simple, will add some images and flex cards which shows the importance/services and also a banner at top?  @ShwetKhatri2001

**Comment by ShwetKhatri2001** [comment]
Okay, looks interesting. Go ahead and make it eye-catching.
