### ISSUE TITLE
Responsive Mobile Design for About Us page

### ISSUE THREAD

**Issue by PSS2134** [ShwetKhatri2001/AR-Webstore#194]
### What's the style idea?

Mobile Responsive #

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ShwetKhatri2001/AR-Webstore/blob/master/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ShwetKhatri2001/AR-Webstore/blob/master/CODE_OF_CONDUCT.md)
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by ShwetKhatri2001** [comment]
You can start working on this.

**Comment by PSS2134** [comment]
Why did you close, I have created a PR now just related to this @ShwetKhatri2001
