### ISSUE TITLE
Wishlist Section

### ISSUE THREAD

**Issue by PSS2134** [ShwetKhatri2001/AR-Webstore#195]
### Description

A Wishlist Section to add items to favourites @ShwetKhatri2001 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines]
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by PSS2134** [comment]
Can you put the feature label

**Comment by ShwetKhatri2001** [comment]
We already have an issue to add cart page. How will this be different than that ?

**Comment by PSS2134** [comment]
This will be only favourites item, for in future buying which can added to cart or removed @ShwetKhatri2001

**Comment by ShwetKhatri2001** [comment]
Okay go ahead, you can add that.

**Comment by ShwetKhatri2001** [comment]
Any updates or issues @PSS2134 ? Today is the last day of `Codepeak23`.

**Comment by PSS2134** [comment]
> Any updates or issues @PSS2134 ? Today is the last day of `Codepeak23`.

yes will do it by today

**Comment by ShwetKhatri2001** [comment]
Are you still working on this @PSS2134 ?

**Comment by ShwetKhatri2001** [comment]
This issue is open for contributions.

**Comment by nandakumarbm26** [comment]
Hello @PSS2134 I am interested to take-up this feature dev.

**Comment by ShwetKhatri2001** [comment]
Sure, go ahead.

**Comment by ayann07** [comment]
Please assign me under swoc 2024

**Comment by ShwetKhatri2001** [comment]
Any updates or issues @nandakumarbm26 ? Please try to complete it in the next 3 days.

**Comment by ShwetKhatri2001** [comment]
Let's give other contributors a chance to work on this.
Assigning this to you @ayann07 since you were the next person who showed interest. Let me know if you have any queries.

**Comment by ShwetKhatri2001** [comment]
@ayann07 Reminding you SWOC contribution period is ending on **`28 Feb`** if you're contributing as part of it.

**Comment by ayann07** [comment]
Yes I have contributed as part of SWOC 2024.

**Comment by ayann07** [comment]
Kindly check and merge the pull request.
