### ISSUE TITLE
[style]: add Button is Not fully rounded on mobile device

### ISSUE THREAD

**Issue by Ayusht777** [ShwetKhatri2001/AR-Webstore#197]
### What's the style idea?

The Add Button on Home Screen gets uneven on mobile devices

### Add screenshots

Add screenshots
![image](https://github.com/ShwetKhatri2001/AR-Webstore/assets/106388215/e93e4fdf-30ca-409b-98cd-263b4be53c27)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ShwetKhatri2001/AR-Webstore/blob/master/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ShwetKhatri2001/AR-Webstore/blob/master/CODE_OF_CONDUCT.md)
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by ShwetKhatri2001** [comment]
If you refresh on mobile viewport width you will get a different view where it's fixed. 
Tell me what else you think can be improved ?

**Comment by prem-prasad1710** [comment]
Hi @ShwetKhatri2001 @Ayusht777 @shanvijha30  ! I'm interested in fixing this issue.
Please assign this issue to me

**Comment by ShwetKhatri2001** [comment]
Closing this issue because it doesn't need a fix.
