### ISSUE TITLE
[style]: Adding animated Loader to the 3D models while they completely load.

### ISSUE THREAD

**Issue by Akshanshkaushal** [ShwetKhatri2001/AR-Webstore#199]
### What's the style idea?

Enhance user experience with a sleek loading animation integrated into your 3D models, providing visual feedback as content loads. Elevate engagement by keeping users informed and entertained during the loading process, ensuring a polished and dynamic interface. In this way, we can Immerse audience in a seamless transition from anticipation to enjoyment as they explore fully-loaded 3D creations.

### Add screenshots

Add screenshots
![Screenshot (158)](https://github.com/ShwetKhatri2001/AR-Webstore/assets/113452367/4758af61-0310-4dc8-b45b-a7b30e52a493)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ShwetKhatri2001/AR-Webstore/blob/master/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ShwetKhatri2001/AR-Webstore/blob/master/CODE_OF_CONDUCT.md)
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by ShwetKhatri2001** [comment]
We have issue #120 where I've mentioned the recommended solution for the issue. You can take a look there.

**Comment by Akshanshkaushal** [comment]
@ShwetKhatri2001 I have seen the issue, can you assign me to work on this issue under swoc'24?

**Comment by ShwetKhatri2001** [comment]
Sure, I'm assigning you that issue. If you want to improve it more than the mentioned requirements there then come back to this issue.

**Comment by ShwetKhatri2001** [comment]
Hey @Akshanshkaushal , I see you've shown interest to work on many issues. But I can assign you one at a time.
So, I'm giving a chance to others for now. You may improve on their implementation later.

**Comment by Akshanshkaushal** [comment]
hey @ShwetKhatri2001 but I have solved this one and implemented the required . Could you please reassign me this.

**Comment by vrun1208** [comment]
Hi @ShwetKhatri2001 , If no one is working on this issue you can assign it to me

**Comment by ShwetKhatri2001** [comment]
Closing this because it's a duplicate issue.
