### ISSUE TITLE
Add ContributingGuidelines.md

### ISSUE THREAD

**Issue by shanvijha30** [ShwetKhatri2001/AR-Webstore#2]
The Contributing Guideline documentation will contain set of guidelines that will help contributors during the contribution process.
File type markdown.

**Comment by shanvijha30** [comment]
@ShwetKhatri2001 could you please assign this issue to me under GSSoC 23
Thank you!

**Comment by ShwetKhatri2001** [comment]
Go ahead @shanvijha30.

**Comment by shanvijha30** [comment]
@ShwetKhatri2001 Could assign this issue to me.

**Comment by shanvijha30** [comment]
Added PR [#26](https://github.com/ShwetKhatri2001/AR-Webstore/pull/26)
Please review it.
