### ISSUE TITLE
[style]:Add Better Navbar in mobile View

### ISSUE THREAD

**Issue by Akshanshkaushal** [ShwetKhatri2001/AR-Webstore#200]
### What's the style idea?

 Elevate the user experience of our AR store by incorporating a sophisticated navigation bar, with visually captivating animations that seamlessly unfold upon opening. This not only ensures functionality but also adds a touch of aesthetic allure to enhance overall engagement.

### Add screenshots

Add screenshots
![nav](https://github.com/ShwetKhatri2001/AR-Webstore/assets/113452367/b08dbca9-01b9-4b0e-827e-7063445db6e2)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ShwetKhatri2001/AR-Webstore/blob/master/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ShwetKhatri2001/AR-Webstore/blob/master/CODE_OF_CONDUCT.md)
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by ShwetKhatri2001** [comment]
Sure, You can work on this @Akshanshkaushal .

**Comment by ShwetKhatri2001** [comment]
Any updates or issues @Akshanshkaushal ? Please try to complete it in the next 3 days.

**Comment by ShwetKhatri2001** [comment]
Let's give other contributors a chance. This issue is open to contributors.

**Comment by KeyurGK** [comment]
@ShwetKhatri2001 Looking forward to contribute to this issue under SWOC

**Comment by ShwetKhatri2001** [comment]
Okay, go ahead.
