### ISSUE TITLE
[style]: About us section is not mobile responsive

### ISSUE THREAD

**Issue by Akshanshkaushal** [ShwetKhatri2001/AR-Webstore#201]
### What's the style idea?

We need to improve the styling of about us page to make it responsive in all devices 

### Add screenshots

Add screenshots
![abou](https://github.com/ShwetKhatri2001/AR-Webstore/assets/113452367/3b2423c4-cf9c-4d2c-9abc-fcf56b2cb8a9)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ShwetKhatri2001/AR-Webstore/blob/master/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ShwetKhatri2001/AR-Webstore/blob/master/CODE_OF_CONDUCT.md)
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by ShwetKhatri2001** [comment]
Hey ! It's a duplicate issue. Check issue #194 . It's already assigned.
