### ISSUE TITLE
[style]: About page Learning and explore section

### ISSUE THREAD

**Issue by Nandini80** [ShwetKhatri2001/AR-Webstore#204]
### What's the style idea?

I can improve the color coding of about page and make it fit to all the screen types.

### Add screenshots

This section can be better
<img width="873" alt="image" src="https://github.com/ShwetKhatri2001/AR-Webstore/assets/121488571/72e49109-17e9-43b0-bddd-5d1c574bf269">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ShwetKhatri2001/AR-Webstore/blob/master/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ShwetKhatri2001/AR-Webstore/blob/master/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by ShwetKhatri2001** [comment]
Sure, I'm assigning you this. Make sure you make it responsive for all viewport widths.
