### ISSUE TITLE
[Feature] Adding animation in about page.

### ISSUE THREAD

**Issue by yashi-15** [ShwetKhatri2001/AR-Webstore#205]
### Description

I want to add animation in the picture in about page.
Please assign this issue to me under SWOC'24.

### Screenshots

![Screenshot (189)](https://github.com/ShwetKhatri2001/AR-Webstore/assets/132138302/489be666-da51-4295-8677-03e5a2f52d65)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines]
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by ShwetKhatri2001** [comment]
Okay, go ahead @yashi-15 . You're assigned.
