### ISSUE TITLE
[BUG] About in footer

### ISSUE THREAD

**Issue by AaadityaG** [ShwetKhatri2001/AR-Webstore#206]
### Description

It leads to github page instead of routing /about

### Screenshots

https://github.com/ShwetKhatri2001/AR-Webstore/assets/114663382/f7ec4617-6b9f-4988-b1af-411cc816b03d

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ShwetKhatri2001/AR-Webstore/blob/master/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

**Comment by zahidgul107** [comment]
can i work on this issue

**Comment by ShwetKhatri2001** [comment]
Okay @AaadityaG , You can fix that.
