### ISSUE TITLE
[style]: improve the hover spans on full screen and help buttons

### ISSUE THREAD

**Issue by RehanChalana** [ShwetKhatri2001/AR-Webstore#209]
### What's the style idea?

We need to improve the position , padding and font size of the span texts

### Add screenshots

![image](https://github.com/ShwetKhatri2001/AR-Webstore/assets/139042983/b7150e87-4c17-4afd-a47f-1a585c769cb6)
![image](https://github.com/ShwetKhatri2001/AR-Webstore/assets/139042983/a4f9c15c-d5ed-4e26-8e02-590efe08c206)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ShwetKhatri2001/AR-Webstore/blob/master/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ShwetKhatri2001/AR-Webstore/blob/master/CODE_OF_CONDUCT.md)
- [X] I'm a SWOC'24 contributor
- [X] I want to work on this issue

**Comment by Tiyasa9** [comment]
I want to work on this issue. I am a SWOC'24 contributor. Kindly assign me this issue.

**Comment by ShwetKhatri2001** [comment]
Yes, it needs improvement. You can work on it.

**Comment by ShwetKhatri2001** [comment]
Any updates or issues @RehanChalana  ? 
Please try to complete it in the next 3 days.

**Comment by RehanChalana** [comment]
Hey i am really sorry , i have not able to work on this issue , you can  feel free to assign it to someone else , I am really sorry

**Comment by ShwetKhatri2001** [comment]
This issue is open to contributors.

**Comment by FlareMozZ** [comment]
I'd like to work on this issue, kindly assign it to me

**Comment by ShwetKhatri2001** [comment]
Okay, go ahead.

**Comment by FlareMozZ** [comment]
I have created a pull request with specified code changes that addressed this issue. Please have a look and let me know
