### ISSUE TITLE
[style]: Feedback page

### ISSUE THREAD

**Issue by Yatin12527** [ShwetKhatri2001/AR-Webstore#214]
### What's the style idea?

I can incorporate images or try color combination to make it look good 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ShwetKhatri2001/AR-Webstore/blob/master/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ShwetKhatri2001/AR-Webstore/blob/master/CODE_OF_CONDUCT.md)
- [X] I'm a SWOC'24 contributor
- [X] I want to work on this issue

**Comment by ShwetKhatri2001** [comment]
Hey, this is a duplicate issue.

**Comment by Yatin12527** [comment]
> Hey, this is a duplicate issue.

so can i get the old issue?

**Comment by ShwetKhatri2001** [comment]
No, it's already assigned.

**Comment by Yatin12527** [comment]
> No, it's already assigned.

Alright apologies

**Comment by ShwetKhatri2001** [comment]
No worries, you can look for other issues.
