### ISSUE TITLE
Addition of Docker 

### ISSUE THREAD

**Issue by Girishbari** [ShwetKhatri2001/AR-Webstore#218]
### Description

I visited the website and GitHub repo, and while skimming through project I wondered that is there any way to get it locally instantly without node modules but there are none, Implementing DockerFile could be a great thing

### Screenshots

![image](https://github.com/ShwetKhatri2001/AR-Webstore/assets/38005544/d478f49b-5a2c-43f8-9e2e-eb6ae809efbd)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines]
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

**Comment by Girishbari** [comment]
@ShwetKhatri2001 what say..?

**Comment by ShwetKhatri2001** [comment]
Can you describe more about how people will be able to setup the project using Docker then?

**Comment by Girishbari** [comment]
I assume you have an understanding of docker, considering this one only needs to run `docker compose run` which installs the dependencies and allows user to run it locally, w/o npm install

**Comment by ShwetKhatri2001** [comment]
Okay, you can work on that.
