### ISSUE TITLE
[BUG] Overlapping template 

### ISSUE THREAD

**Issue by AbhineshJha** [ShwetKhatri2001/AR-Webstore#219]
### Description

Whenever we hover upper template , it's hovering effect overlapping the bottom template .
i wanna work in this issue can u assign me under SWOC 24

### Screenshots

https://github.com/ShwetKhatri2001/AR-Webstore/assets/142514166/424fd614-6fc0-497e-9193-ff1b1867bbb1

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ShwetKhatri2001/AR-Webstore/blob/master/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

**Comment by ShwetKhatri2001** [comment]
Okay, fix that. Probably don't remove the border-bottom but keep it just below the image so that it doesn't overlap.
