### ISSUE TITLE
I have some ideas to make the website look even cooler and easier to use.

### ISSUE THREAD

**Issue by AjayAsnani** [ShwetKhatri2001/AR-Webstore#222]
### What's the style idea?

Here's what I'm thinking:

1)-Fresh Look: Give it a more modern style, like using new fonts and arranging things more cleanly. 

2)-Clear Focus: Make the important parts stand out more, so people can find what they need quickly.

3)-Perfect Fit: Make sure it looks great on phones, tablets, and computers.

4)-Fun Touches: Add some little animations and surprises to make it more fun to use.

What do you think?
I'm open to all ideas, so let's chat about it!

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ShwetKhatri2001/AR-Webstore/blob/master/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ShwetKhatri2001/AR-Webstore/blob/master/CODE_OF_CONDUCT.md)
- [X] I'm a SWOC'24 contributor
- [X] I want to work on this issue

**Comment by ShwetKhatri2001** [comment]
The description is very generic. Please provide specific types of changes you want to make along with examples.

**Comment by ShwetKhatri2001** [comment]
Any updates or issues @AjayAsnani ? Please try to complete it in the next 3 days.

**Comment by ShwetKhatri2001** [comment]
Closing it because of inactivity.
