### ISSUE TITLE
[Feature] Enhancing contributors section.

### ISSUE THREAD

**Issue by yashi-15** [ShwetKhatri2001/AR-Webstore#223]
### Description

- The contributor's section in About page has a single image within which every contributor is listed. 
- I would like to change to it, to separate every contributor and add appropriate styling and hover effects to each contributor in contributors list. 

Assign this issue to me under SWOC.

### Screenshots

![Screenshot (204)](https://github.com/ShwetKhatri2001/AR-Webstore/assets/132138302/f576ec11-9b5a-4752-a51b-adea7762fe92)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines]
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

**Comment by ShwetKhatri2001** [comment]
I'd like to know if you'd be able to keep it dynamic such as new contributors also gets added there. Since that's also important.

**Comment by yashi-15** [comment]
Sure, I'll do it! @ShwetKhatri2001

**Comment by ShwetKhatri2001** [comment]
Assigning you this.
