### ISSUE TITLE
[style]: Add a relevant logo on Navbar

### ISSUE THREAD

**Issue by Ishita928** [ShwetKhatri2001/AR-Webstore#240]
### What's the style idea?

We need to improve:
A logo needs to be added on navbar to make it look more appealing

### Add screenshots

Add screenshots
![image](https://github.com/ShwetKhatri2001/AR-Webstore/assets/146575485/ec069afe-cb42-4d16-9aa8-e2cbf2f8785c)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ShwetKhatri2001/AR-Webstore/blob/master/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ShwetKhatri2001/AR-Webstore/blob/master/CODE_OF_CONDUCT.md)
- [X] I'm a SWOC'24 contributor
- [X] I want to work on this issue

**Comment by ShwetKhatri2001** [comment]
We already have issue #224 . You may contribute to that after the current assigned person in few days.

**Comment by ShwetKhatri2001** [comment]
Closing this because it's a duplicate. @Ishita928 you may comment on that issue if you want to work on it.
