### ISSUE TITLE
[style]: UI Problem of SignIn and Signup Page

### ISSUE THREAD

**Issue by amansgith** [ShwetKhatri2001/AR-Webstore#247]
## Problem
The SignIn and SignUp Cards are positioned wrongly and are taking over the space of Navigation Bar. Especially the SignUp cards is even hiding the home element of the Navigation Bar
This is a problem in the responsive design also because the navbar hides behind the cards and creates difficulty in accessibility.

## Solution
I have figured out the problem and can fix it quickly and hence would like to work on this issue

Thank you

### Desktop Pages
<img width="953" alt="ss1" src="https://github.com/ShwetKhatri2001/AR-Webstore/assets/104363876/1017cb9e-7169-45a5-8cb6-b8cb98ab497d">
<img width="959" alt="ss2" src="https://github.com/ShwetKhatri2001/AR-Webstore/assets/104363876/ba287fd6-a334-4fac-b9f2-0d74e60706e6">

### Mobile Pages Video Recording

https://github.com/ShwetKhatri2001/AR-Webstore/assets/104363876/ed7dfcae-e65d-48c1-89a2-bb47240eee14

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ShwetKhatri2001/AR-Webstore/blob/master/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ShwetKhatri2001/AR-Webstore/blob/master/CODE_OF_CONDUCT.md)
- [X] I'm a SWOC'24 contributor
- [X] I want to work on this issue

**Comment by ShwetKhatri2001** [comment]
Okay, go ahead and fix it. Changing the dimension of the form container responsively will make it better.
