### ISSUE TITLE
[Add] CONTRIBUTING.md

### ISSUE THREAD

**Issue by bhartik021** [ShwetKhatri2001/AR-Webstore#28]
### Description

This commit updates the `CONTRIBUTING.md` file in the repository to provide clear guidelines for contributing to the project. The changes include the following:

- Added a section on how to report bugs and issues, including steps for reproducing them and providing relevant information.
- Included instructions on how to suggest new features or improvements, including the preferred format for feature requests.
- Clarified the code formatting and style guidelines to ensure consistency across contributions.
- Provided examples and explanations on how to submit pull requests, along with the necessary steps for the review process.
- Added a section on how to communicate effectively with the project maintainers and other contributors, emphasizing the importance of respectful and constructive discussions.

> These updates aim to streamline the contribution process and provide contributors with clear instructions on how to get involved. The goal is to foster a welcoming and collaborative environment for anyone interested in contributing to the project.

### Screenshots

![screenshot](https://github.com/ShwetKhatri2001/AR-Webstore/assets/75694208/bfded018-1a8e-480d-90f9-e5e1a6f8d7f6)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines]
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by ShwetKhatri2001** [comment]
Hi @bhartik021 ! Thanks for raising this issue and providing some good suggestions. But we already have PR #26 adding `CONTRIBUTING.md` file, so wait till it get merged. Then you can put your changes on it.

**Comment by ShwetKhatri2001** [comment]
@bhartik021 You can work on this issue if you want to enhance current CONTRIBUTING.md

**Comment by Snigdha2712** [comment]
Kindly assign this issue to me under gssoc23 @ShwetKhatri2001
