### ISSUE TITLE
enhancement in button styles 

### ISSUE THREAD

**Issue by Amankumarharsh** [ShwetKhatri2001/AR-Webstore#3]
I want to change buttons styles of website in more vibrant way .Pls assign this issue so I start contributing. Or if you have an some other issue in front end pls let me known and assign it to me.

**Comment by ShwetKhatri2001** [comment]
Sure @Amankumarharsh. I hope you will actually make it vibrant! Go ahead.

**Comment by vishnubansal001** [comment]
i also want to contribute on this please allow me to contribute please @ShwetKhatri2001

**Comment by sagnik-p** [comment]
This issue has been inactive for a long time
I would like to work on this issue
Please assign

**Comment by ShwetKhatri2001** [comment]
Are you working on this issue @Amankumarharsh ? 
If yes, then please create a PR with your changes in the next 2 days, so that other contributors can also give it a try after that.

**Comment by ShwetKhatri2001** [comment]
I have decided to go with React App now to have an easy set-up for everyone.
Also, our UI is completely changed now and there are no buttons that require enhancement. 

Let me know what you guys have to say, else I'd like to close this issue. 
There are many new ways open for you guys now to contribute.

**Comment by ShwetKhatri2001** [comment]
Closing this issue because it has been inactive for a long time and is not so relevant to the project now.
