### ISSUE TITLE
[BUG] Fix spelling and grammatical errors in the READMe.md file

### ISSUE THREAD

**Issue by IfeoluwaAroboto** [ShwetKhatri2001/AR-Webstore#30]
### Description

1. In the "Current State of Project" section, "ecommerse" should be "e-commerce."
2. In the "Solution" section, "more clearly" should be "clearly."
3. In the "Future Goals" section, "ecommerse" should be "e-commerce."

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by kartik-0908** [comment]
Please assign me this issue, I would love to work on this

**Comment by ShwetKhatri2001** [comment]
Okay, Go ahead with your changes @IfeoluwaAroboto ! Assigning you this issue.

**Comment by Snigdha2712** [comment]
Kindly assign it to me @ShwetKhatri2001 . I would like to work on this issue under gssoc23

**Comment by SayandevSantra** [comment]
Could you assign me this issue i would love to work on it .

**Comment by ShwetKhatri2001** [comment]
The errors mentioned in this issue's description are mostly solved now.
So, just want to ask @IfeoluwaAroboto, if you are not working on this now, then I'm actually thinking of closing this issue.

**Comment by ShwetKhatri2001** [comment]
Closing the issue, since all the mentioned tasks are mostly solved under other issues.
