### ISSUE TITLE
[BUG] Fix  grammatical error in the readme.md

### ISSUE THREAD

**Issue by thakurdiwakar** [ShwetKhatri2001/AR-Webstore#31]
### Description

In the README file under the "Current State of Project" heading, the correct sentence would be:

"Current State of Project: It showcases a 3D photorealistic model of a chair in your own environment using augmented reality, where you can check each and every detail about the chair as if it's actually present in your room."

 The word "its" should be replaced with "it's" to indicate the contraction of "it is."

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by ShwetKhatri2001** [comment]
Please find some other types of changes you can make to the project since we already have a similar issue #30 which can cover this bug.

**Comment by thakurdiwakar** [comment]
But check #30 issue is in different  line

**Comment by ShwetKhatri2001** [comment]
Yes, but find and add some other small issues. So, that I can review and merge them all at once.

**Comment by mfatima05** [comment]
Please assign me #30 and #31 issue

**Comment by thakurdiwakar** [comment]
I have found one more mistake. 'Opensource Programs' – this heading should be capitalized

Please assign me

**Comment by ShwetKhatri2001** [comment]
> I have found one more mistake. 'Opensource Programs' – this heading should be capitalized
> 
> Please assign me @ShwetKhatri2001

It's already correct I guess and matching other titles.

**Comment by mfatima05** [comment]
please assign me #30 and #31 issue

**Comment by ShwetKhatri2001** [comment]
> [Opensource Programs](https://github.com/ShwetKhatri2001/AR-Webstore#open-source)
> 
> See again

I wanted to say that it's already in the right form and if you want to make all characters capitalized, then it will not follow the standard of writing such documentation.
