### ISSUE TITLE
Updation of front web View of Page landing

### ISSUE THREAD

**Issue by Cdggtt** [ShwetKhatri2001/AR-Webstore#33]
### Description

I think we have change the background color and It also available in desktop also . Could You please assign me this task for GSSOC 23.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines]
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by ShwetKhatri2001** [comment]
Can you please elaborate on which issue/enhancement you're talking about.

**Comment by ShwetKhatri2001** [comment]
Closing this issue because it's looking irrelevant for the new React app.
