### ISSUE TITLE
Adding error 404 page

### ISSUE THREAD

**Issue by VC6378** [ShwetKhatri2001/AR-Webstore#34]
### Description

Hey,
I want to add an error 404 page to the website.
Thanks and Regards,
Vibhuti Chandrakar.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines]
- [x] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by ShwetKhatri2001** [comment]
Okay, Go ahead and add it! Make sure the 404 page gets rendered when the entered path / URL doesn't exist on our website.

**Comment by VC6378** [comment]
Hello @ShwetKhatri2001,
Is there any way I could contact to you, I need some help.

**Comment by ShwetKhatri2001** [comment]
If you're a GSSoC'23 contributor, You can join their discord server. Then just react to AR-Webstore from self-roles and you will get access to the project channel where you can resolve your doubts and get help.

**Comment by ShwetKhatri2001** [comment]
I have decided to go with React App now, so kindly pull the latest master branch and make your changes on that accordingly.

Also, @VC6378  please try to complete the changes for this issue in the next two days, after that, I'd like to give the opportunity to work on this issue to someone else

**Comment by VC6378** [comment]
Alright sir, will get it done by tomorrow.

**Comment by VC6378** [comment]
@ShwetKhatri2001, the website is single page, why will i be adding error 404 page to it??

**Comment by ShwetKhatri2001** [comment]
You can use React-Router to handle that on which URL route which page you want to show,
Ref : https://reactrouter.com/en/main/start/overview

You will also find some examples on internet about how to add 404 page using react-router.

**Comment by PatilHarshh** [comment]
hey @VC6378 let do it in collaboration if finding difficulty @ShwetKhatri2001

**Comment by ShwetKhatri2001** [comment]
@PatilHarshh if you want to collaborate on this issue then you can add the react-router having a home page and 404 error page.
So that she can then change that 404 page easily. You will be provided level-1 for this implementation.

**Comment by PatilHarshh** [comment]
ok @ShwetKhatri2001

**Comment by PatilHarshh** [comment]
@ShwetKhatri2001 three and react router dom is conflicting unable to download the package

**Comment by PatilHarshh** [comment]
@ShwetKhatri2001 done

**Comment by PatilHarshh** [comment]
@VC6378 you can proceed now

**Comment by ShwetKhatri2001** [comment]
@VC6378 You can update your PR now, you shouldn't be getting any errors now.

**Comment by mandliyarajendra11** [comment]
@ShwetKhatri2001 i can work on this issue ???

**Comment by mandliyarajendra11** [comment]
@ShwetKhatri2001 please reply

**Comment by ShwetKhatri2001** [comment]
Any updates or issues @VC6378  ?
Please try to complete the requested changes and update your PR within the next 3 days.
After that, This issue will be open to other interested contributors.

**Comment by mandliyarajendra11** [comment]
> Any updates or issues @VC6378 ? Please try to complete the requested changes and update your PR within the next 3 days. After that, This issue will be open to other interested contributors.

???

**Comment by ShwetKhatri2001** [comment]
Let's give other contributors a chance to work on this issue now.  As @mandliyarajendra11 you showed some interest to work on this issue, I'm assigning you this issue.

**Comment by mandliyarajendra11** [comment]
> Let's give other contributors a chance to work on this issue now.  As @mandliyarajendra11 you showed some interest to work on this issue, I'm assigning you this issue.

okay
