### ISSUE TITLE
Adding a feedback section

### ISSUE THREAD

**Issue by khushi1711** [ShwetKhatri2001/AR-Webstore#35]
### Description

-

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines]
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by ShwetKhatri2001** [comment]
Please provide more context about what changes you are going to make.

**Comment by mfatima05** [comment]
The feedback section will include a space for users or visitors to provide their comments, suggestions, and opinions about the website's design, functionality, content, and overall user experience. I will work on this. Kindly assign me this issue @ShwetKhatri2001

**Comment by ShwetKhatri2001** [comment]
@mfatima05 I'd like to go with your ideas. So, go ahead and make the changes you've proposed. You're assigned.

**Comment by mfatima05** [comment]
thank you sir
I will work on this

**Comment by ShwetKhatri2001** [comment]
I have decided to go with React App now, so kindly pull the latest master branch and make your changes on that accordingly.

**Comment by ShwetKhatri2001** [comment]
Any updates or issues @mfatima05 ? Please try to make your changes and create a pull request in the next 3 days.

**Comment by ShwetKhatri2001** [comment]
This issue is open to all contributors now.

**Comment by shraddha761** [comment]
@ShwetKhatri2001 Will you please assign this issue to me

**Comment by akanksha984** [comment]
@ShwetKhatri2001 Please assign this issue to me i am ready to work on this

**Comment by ShwetKhatri2001** [comment]
@akanksha984 Assigning you this issue since you're done with your previous issues.
Go through the previous comments to know better about the outcomes. Ask queries if you have any.

**Comment by akanksha984** [comment]
@ShwetKhatri2001 what fields are required ?

**Comment by ShwetKhatri2001** [comment]
You can have some input boxes to answer some questions as follows,

- What did you like the most about AR-Webstore ?
- Will our 3D and AR features improve your shopping experience if we integrate it on an online e-commerce store ?
- What are the other features that excites you to have them on AR-Webstore ?
- Any other comments?

**Comment by ShwetKhatri2001** [comment]
Any updates or issues @akanksha984 ?

**Comment by akanksha984** [comment]
Yes @ShwetKhatri2001 tomorrow I will create pr for both the issues

**Comment by akanksha984** [comment]
![image](https://github.com/ShwetKhatri2001/AR-Webstore/assets/97845909/c8e50b2b-6565-4f69-9320-bd9ff63a9556)
![image](https://github.com/ShwetKhatri2001/AR-Webstore/assets/97845909/e8c640fb-5ad5-4f6f-92dc-853f0e0206c3)

Fully responsive
@ShwetKhatri2001 please have a look
