### ISSUE TITLE
[BUG] <Add new greetings.yml>

### ISSUE THREAD

**Issue by shivam-sharma7** [ShwetKhatri2001/AR-Webstore#39]
### Description

current greetings.yml not working add new one for new contributors who open their first issue, merged first PR

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by ShwetKhatri2001** [comment]
Okay, correct it. You're assigned.
