### ISSUE TITLE
[BUG] Fix grammatical error in README.md

### ISSUE THREAD

**Issue by Aishjahan** [ShwetKhatri2001/AR-Webstore#41]
### Description

Line 8: "ecommerse" should be "ecommerce" (spelling error).

Line 9: "Make the products interactive in real-environment" should be "Make the products interactive in a real environment" (missing article and hyphen error).

Line 12: "programming technologies like Three.JS or Unity" should be "programming technologies like Three.js or Unity" (capitalization error).

Line 44: "This project is a part of following Open Source Program" should be "This project is a part of the following Open Source Program" (missing "the" and capitalization error).

### Any additional information?

Please assign me this issue under GSSoC.

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by ShwetKhatri2001** [comment]
Go ahead @Aishjahan ! Also, include issue #42 in a single PR. You're assigned.

**Comment by mfatima05** [comment]
There are mistakes in Enforcement paragraph. 
kindly do assign me this issue
