### ISSUE TITLE
[BUG] <Error got when `npm start:live` >

### ISSUE THREAD

**Issue by shivam-sharma7** [ShwetKhatri2001/AR-Webstore#47]
### Description

when I run `npm start:live` then it's not working so we need to run `npm start` instead `npm start:live`
`npm start` is working fine
 
![image](https://github.com/ShwetKhatri2001/AR-Webstore/assets/91419219/049f9b33-7f6e-4d01-a246-1ec64039a046)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by ShwetKhatri2001** [comment]
It's `npm run start:live` actually. Would you like to change it in the documentation ?

**Comment by shivam-sharma7** [comment]
yes

**Comment by ShwetKhatri2001** [comment]
Okay, I'm assigning you this issue. Make the change.
