### ISSUE TITLE
Improve ReadMe.md

### ISSUE THREAD

**Issue by VSatwika** [ShwetKhatri2001/AR-Webstore#5]
- I can add badges to ReadMe.md
   Could you assign this to me as a part of GSSoC'23?
   Thank You

**Comment by ShwetKhatri2001** [comment]
Sure @VSatwika You can add the badges. But to keep this issue separate from #9 , it will be good if you can add some badges except the ones for the tech stack. You're assigned. Keep contributing 🎉

**Comment by Gun2902** [comment]
can u assign me this isssue
