### ISSUE TITLE
Improving the README.md

### ISSUE THREAD

**Issue by the-amazing-atharva** [ShwetKhatri2001/AR-Webstore#50]
Hello there!
I would like to work on the README.md to make it more visually appealing and coherent.
I will:
+ restructure the header
+ better styling of content
+ format the text in a better manner
+ add badges 
+ etc.

Do assign me for **GSSOC'23** if approved

**Comment by ShwetKhatri2001** [comment]
Okay, Go ahead. I'm expecting you will make it stand out with your changes.

**Comment by the-amazing-atharva** [comment]
Working on it!

**Comment by ShwetKhatri2001** [comment]
Closing this because the proposed changes are not required now.
