### ISSUE TITLE
[UI] <Adding the UI to look more attractive>

### ISSUE THREAD

**Issue by iamparas0** [ShwetKhatri2001/AR-Webstore#56]
### Description

I would like to add UI in the site so it will not look untill and managing text size according to responsiveness of the site, please assign it to me.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines]
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by ShwetKhatri2001** [comment]
Sure, Go ahead @iamparas0 ! You're assigned.

**Comment by MohamedMafaz** [comment]
Hey @ShwetKhatri2001 
Can you assign me to any UI design related issue please?

**Comment by ShwetKhatri2001** [comment]
I have decided to go with React App now, so kindly pull the latest master branch and make changes on that accordingly.

Also, @iamparas0 please try to complete the changes for this issue in next two days, so that others can also work on it.

**Comment by iamparas0** [comment]
Sorry for the delays , i was busy in my mid semester . i will complete it soon .

**Comment by iamparas0** [comment]
> Any updates or issues @iamparas0 ? ( if you're still working on this issue. ) Please try to make your changes and raise your PR within the next 3 days. After that, This issue will be open to other interested contributors.

please close this issue .
