### ISSUE TITLE
[Feature] Remove the contributing steps from readme.md file

### ISSUE THREAD

**Issue by sumitkr2000** [ShwetKhatri2001/AR-Webstore#58]
### Description

Hey, @ShwetKhatri2001 The contributing.md file already contains all the steps for contribution. So there is no need to keep these steps in readme.md file. So I want to remove it. Please assign me this issue. Thank you!

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines]
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by ShwetKhatri2001** [comment]
I think for an open-source project the steps to setup the project has to be on README.md as well, since its the first reference for anyone trying out the project.

**Comment by sumitkr2000** [comment]
ok ok cool np!
