### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by VSatwika** [ShwetKhatri2001/AR-Webstore#6]
- I would like to request the addition of a code of conduct to the repository.
 - Having a code of conduct is essential to establish a welcoming and inclusive environment for all contributors.
 - It provides clear guidelines for expected behavior and helps create a safe and respectful space for collaboration.
 
   I am contributing under GSSoC'23. Could this issue be assigned to me?

**Comment by ShwetKhatri2001** [comment]
Good idea @VSatwika ! Go ahead. I'm assigning you this issue.
