### ISSUE TITLE
[ADD] Change of Favicon

### ISSUE THREAD

**Issue by varunlmxd** [ShwetKhatri2001/AR-Webstore#63]
### Description

Changing the favicon with a logo.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines]
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by ShwetKhatri2001** [comment]
Okay, Go ahead. 
Try to have an eye-catching favicon matching our project idea.
