### ISSUE TITLE
[Feature] Redesign the Product Card

### ISSUE THREAD

**Issue by ShwetKhatri2001** [ShwetKhatri2001/AR-Webstore#64]
### Description

We already have a `ModelViewer` component having a 3D viewer and QR code ( for desktop ). 
Just convert it to a well-designed card having both a 3D viewer and OR code combined.
It should be responsive for all viewports and the component should be reusable. 

### Screenshots

- It should look like a product card on an e-commerce platform. Let's create a card as given below with some changes.

![image](https://github.com/ShwetKhatri2001/AR-Webstore/assets/56475750/6b9359c0-1e6f-403c-a714-e38c46bff3ea)

**For mobile**
Create a card in which 50% height will be for our viewer and the other 50% for other product details / actions having UI shown in the image. 

**For Desktop**
Keep other things in card similar as explained above ( for mobile ), just add this section below product details.
![image](https://github.com/ShwetKhatri2001/AR-Webstore/assets/56475750/456b75e7-c0b9-49b3-a937-8c4d0a053541)
You can remove that URL and narrow down this section as shown above.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines]
- [ ] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by tanisha2202** [comment]
Greetings! I would like to work on this issue. Please assign it to me.

**Comment by ShwetKhatri2001** [comment]
Of course, Go ahead! Apply your creativity to the next level. 
Also, try to complete it within next 5 days. You're assigned.

**Comment by ShwetKhatri2001** [comment]
Any updates or issues @tanisha2202 ? Please try to complete your changes by this weekend.
After that, it will be open to other contributors.

**Comment by ShwetKhatri2001** [comment]
Any updates or issues @shraddha761 ?
Please try to complete the requested changes and update your PR within the next 3 days.
After that, This issue will be open to other interested contributors.

**Comment by shraddha761** [comment]
@ShwetKhatri2001 I'll text you at discord please check your dm

**Comment by ShwetKhatri2001** [comment]
Let's give other contributors a chance to work on this issue. This issue is open to be assigned now.
I've updated the description to clear the objectives.

**Comment by akanksha984** [comment]
@ShwetKhatri2001 Please assign this to me under gssoc'23. I am ready to work on this issue in time

**Comment by ShwetKhatri2001** [comment]
@akanksha984 You've shown interest to work on multiple issues, but I can only assign you 2 issues at a time.
There is one already assigned and one is left. 

Let me know which issue you want to pick up next from the issues where you've commented.
This issue has been our high priority. So, It'd be good if you can pick this. But the final decision is yours.

**Comment by ShwetKhatri2001** [comment]
Instead of the shoe image above we will have this whole 3D viewer ( nothing to be removed ),
![image](https://github.com/ShwetKhatri2001/AR-Webstore/assets/56475750/d5e134e5-bc9d-4c85-99e5-52333dbaa677)

You can add other things required for product details or actions. Apply your creativity freely, I've just provided an example.

**Comment by akanksha984** [comment]
Ok I will try designing it

**Comment by akanksha984** [comment]
![image](https://github.com/ShwetKhatri2001/AR-Webstore/assets/97845909/158682a1-54e4-47a6-a8ba-3a2c6f0f0bcf)
![image](https://github.com/ShwetKhatri2001/AR-Webstore/assets/97845909/e4aedb90-08d3-4d86-b7be-72622ea0d433)

Please check it @ShwetKhatri2001

**Comment by ShwetKhatri2001** [comment]
The colors used here can be better. 

Make the styles like this, ( I just changed some CSS in browser's developer-tools and got this )

![image](https://github.com/ShwetKhatri2001/AR-Webstore/assets/56475750/0a524ac6-b350-4999-bf5a-8327fdfe56c4)

Complete these and you will be done after that,
- Make the card smaller ( around 350 in width ) since we will have multiple cards on this page later
- Stick to 3-4 main colors. ( `#eee`, `#ddd`,`rgba(235,88,51,0.75 )`  and `#aaa` you may use )
- Remove the `URL` as mentioned in this issue's description
- Show those three details above the QR code row in this order - Product Name, Rating, and Price.

**Comment by akanksha984** [comment]
Same card color I created earlier so that it looks formal but then I changed it to bright colors. 
Ok I will do the required changes and create the pr for it @ShwetKhatri2001

**Comment by akanksha984** [comment]
![image](https://github.com/ShwetKhatri2001/AR-Webstore/assets/97845909/8e804539-250b-4847-94c0-5de3e825b604)

@ShwetKhatri2001 looks well??

**Comment by akanksha984** [comment]
please check this @ShwetKhatri2001
