### ISSUE TITLE
Browser isn't supporting.

### ISSUE THREAD

**Issue by StarKnightt** [ShwetKhatri2001/AR-Webstore#8]
I think this is not supported in Mozilla Firefox 😅
![image](https://github.com/ShwetKhatri2001/AR-Webstore/assets/92244026/b7444160-f367-4bb5-9dec-b89f6ac377db)

**Comment by crocmons** [comment]
also not supported in chrome

**Comment by vishnubansal001** [comment]
i want to work on this issue please allow me to work on this issue @ShwetKhatri2001 please allow me as i am a GSSOC'23 contributor

**Comment by arunavabasu-03** [comment]
I would like to work on this!

**Comment by Saloni581** [comment]
Could you please assign me this issue. I want to work on it under GSSoC'23.

**Comment by ShwetKhatri2001** [comment]
I have decided to go with React App now because of many common issues in set-up and running the project in old tech stack.
This issue doesn't exist now actually, so closing it. 

Thanks for showing your interest here everyone 👍
