### ISSUE TITLE
[Feature] Name of the website

### ISSUE THREAD

**Issue by mandliyarajendra11** [ShwetKhatri2001/AR-Webstore#84]
### Description

change website name React App to AR-Webstore
and add some description about the website into the meta tag

1. add some meta tag like description ,  keyword for meta score
2. change website name
3.  i can add chair and all item into the center 
using display flex 
4. back-to-top button in readme.md

can you assign me this issue with level-2 label

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines]
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by ShwetKhatri2001** [comment]
That's good. But it will be even better if you can find some more enhancements and include them in a single PR.

**Comment by mandliyarajendra11** [comment]
> That's good. But it will be even better if you can find some more enhancements and include them in a single PR.

1. add some meta tag like description ,  keyword for meta score
2. change website name
3 . 
i can add chair and all item into the center 
using display flex 

can you assign me this issue with level-2 label

**Comment by ShwetKhatri2001** [comment]
Okay! 
But I guess a back-to-top button is not required since the page is not having a lot of content. 
But you can add the others for level-1. Let me know if you want to work accordingly.

**Comment by mandliyarajendra11** [comment]
> Okay! But I guess a back-to-top button is not required since the page is not having a lot of content. But you can add the others for level-1. Let me know if you want to work accordingly.
back to top button in readme.md 

readme.md have lot of content

**Comment by mandliyarajendra11** [comment]
![Screenshot (144)](https://github.com/ShwetKhatri2001/AR-Webstore/assets/119125519/6b58aae4-0e4a-4639-b832-a71efbeaf799)
 like this

**Comment by mandliyarajendra11** [comment]
@ShwetKhatri2001  please assign me this issue

**Comment by ShwetKhatri2001** [comment]
> ![Screenshot (144)](https://user-images.githubusercontent.com/119125519/248489438-6b58aae4-0e4a-4639-b832-a71efbeaf799.png) like this

Let's keep this `back to top` documentation change in a separate issue, you can raise it if you want.
I'm assigning you this issue for the other three tasks here. Go ahead!

**Comment by mandliyarajendra11** [comment]
> > ![Screenshot (144)](https://user-images.githubusercontent.com/119125519/248489438-6b58aae4-0e4a-4639-b832-a71efbeaf799.png) like this
> 
> Let's keep this `back to top` documentation change in a separate issue, you can raise it if you want. I'm assigning you this issue for the other three tasks here. Go ahead!

okay
