### ISSUE TITLE
creating a footer section 

### ISSUE THREAD

**Issue by gaur15** [ShwetKhatri2001/AR-Webstore#87]
### Description

In footer section copyright line and adding social media profiles

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines]
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by ShwetKhatri2001** [comment]
Any updates or issues @gaur15 ?

**Comment by gaur15** [comment]
> Any updates or issues @gaur15 ?
only some work is left sorry for the delay but I will complete in 1-2 days

**Comment by Kajal2468** [comment]
I want to add some more functionality in footer part . please assing this issue in under GSSoc'23

Thank You!

**Comment by ShwetKhatri2001** [comment]
@gaur15 Please try to make your changes and create a PR within the next 3 days.
After that, This issue will be open to other interested contributors.

**Comment by Kajal2468** [comment]
please assign this issue in under GSSoc'23 , I want to work on this issue

**Comment by ShwetKhatri2001** [comment]
@Kajal2468 There is an open PR for this issue, let it get merged first. After that, you can work on this issue.

@gaur15 I've requested some changes on your PR, please go thought that.

**Comment by ShwetKhatri2001** [comment]
Let's give other contributors a chance to work on this issue. This issue is open to be assigned now.

@Kajal2468 , You showed interest in working on this issue earlier. Would you like to work on this now ?

**Comment by Kajal2468** [comment]
yes @ShwetKhatri2001 I want to work on this issue pls assign it to me.

Thank You!!

**Comment by ShwetKhatri2001** [comment]
Okay, You're assigned. You can start working on this and please try to complete it within the next 5 days.

**Comment by Kajal2468** [comment]
ok

**Comment by tanujbordikar** [comment]
I wanted to work on this issue!
