### ISSUE TITLE
add tech stack badges/shields

### ISSUE THREAD

**Issue by mridulsaggi** [ShwetKhatri2001/AR-Webstore#9]
i would like to add the tech stack shields in the readme file.
this will give a quick view of all the techstacks used in the project
@ShwetKhatri2001  pls assign me this issue . i am a gssoc contributor
example of the tech stack:
![image](https://github.com/ShwetKhatri2001/AR-Webstore/assets/91930535/c191cdac-2bbc-4d82-b92f-8b34e30da42f)

**Comment by ShwetKhatri2001** [comment]
Go ahead with your proposed changes @mridulsaggi
