### ISSUE TITLE
Improvements to contribution.md

### ISSUE THREAD

**Issue by PurviSaini** [ShwetKhatri2001/AR-Webstore#94]
Description
# I would like to add some below mentioned improvements to contribution.md documentation:

### From this 
---
![Screenshot (100)](https://github.com/ShwetKhatri2001/AR-Webstore/assets/101940722/15b72063-77a6-413c-a9ea-c2d53e96bf7b)
---
 ### To this
---
![Screenshot (101)](https://github.com/ShwetKhatri2001/AR-Webstore/assets/101940722/fe263cf2-f829-4be0-9373-aec5ed5d2711)
---
### From this
---
![Screenshot (103)](https://github.com/ShwetKhatri2001/AR-Webstore/assets/101940722/7eeedde6-b346-48ff-9b14-feae3e7b42d5)
---

### To this
---
![Screenshot (102)](https://github.com/ShwetKhatri2001/AR-Webstore/assets/101940722/d6c0b73c-b17a-4881-9105-2df440c40325)
---

Checklist
- [x] I have checked the existing issues
- [x] I have read the [Contributing Guidelines]
- [x] I am willing to work on this issue (optional)
- [x] I am a GSSoC'23 contributor

**Comment by ShwetKhatri2001** [comment]
Okay, go ahead @PurviSaini! Looks like you've found some interesting changes to be made. You're assigned.

**Comment by PurviSaini** [comment]
I am on it.
