### ISSUE TITLE
[Feature] Enable lazy loading to improve website performance

### ISSUE THREAD

**Issue by shraddha761** [ShwetKhatri2001/AR-Webstore#95]
### Description

Lazy loading is a technique that can be used to improve the performance of a website by delaying the loading of images and other resources until they are needed. This can help to reduce the initial load time of a page, which can improve the user experience and make the website more responsive.

The benefits of lazy loading include:

Reduced initial load time
Improved user experience
More responsive website
Increased SEO ranking

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines]
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by ShwetKhatri2001** [comment]
This is a good to have feature, but not now specially when we don't have any images on our website.
Maybe we can work on this later. For now, you can look for some other features to be developed / issues to be solved.

**Comment by ayann07** [comment]
I would like to work under SWOC 2024

**Comment by ShwetKhatri2001** [comment]
Go ahead @ayann07 ! You may add lazy-loading for images present on the home page and about page.

**Comment by ShwetKhatri2001** [comment]
Any updates or issues @ayann07 ? Please try to complete it in the next 3 days.
