### ISSUE TITLE
[Feature] Full screen mode for 3D Viewer

### ISSUE THREAD

**Issue by ShwetKhatri2001** [ShwetKhatri2001/AR-Webstore#96]
### Description

Add a button near/on the 3D viewer card present currently which should show the 3D viewer on the entire screen with all controls working there to give the user a broader view of the product in 3D. Also, using the same button the user should be able to get out of that full-screen mode.

### Screenshots

Go through this [Sketchfab example](https://sketchfab.com/3d-models/oversized-drop-shoulder-sweatshirt-c533289593ed4a7094bc2e0cefebde12), we can have a similar full-screen button present at the right-bottom functioning similarly.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines]
- [ ] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by shraddha761** [comment]
@ShwetKhatri2001 I can work on this issue will you please assign this issue to

**Comment by mandliyarajendra11** [comment]
@ShwetKhatri2001 please assign me this issue

**Comment by ShwetKhatri2001** [comment]
You both are already assigned to one issue and I can't assign another until those get completed.

**Comment by mandliyarajendra11** [comment]
> You both are already assigned to one issue and I can't assign another until those get completed.

done bro issue #97

**Comment by varshanim** [comment]
@ShwetKhatri2001 I would like to work on this issue. Can you please assign it to me?

**Comment by ShwetKhatri2001** [comment]
@mandliyarajendra11 you can start working on this now. You're assigned.
