### ISSUE TITLE
[Feature] Add instructions screen for 3D viewer

### ISSUE THREAD

**Issue by ShwetKhatri2001** [ShwetKhatri2001/AR-Webstore#97]
### Description

We can have a button near / on the 3D viewer card which opens up a new screen on the viewer as an overlay having the basic instructions about how to use it. This feature can really help the users who are new to such 3D product viewers.

### Screenshots

Go through this [Sketchfab example](https://sketchfab.com/3d-models/oversized-drop-shoulder-sweatshirt-c533289593ed4a7094bc2e0cefebde12), we can have a similar `Help` button present at the right-bottom opening a new screen having the controls shown in `Navigation Basics`.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines]
- [ ] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by mandliyarajendra11** [comment]
i want  to work on this issue please assign me

**Comment by ShwetKhatri2001** [comment]
Okay, Go ahead. Apply your creativity freely. You're assigned.
